/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jeremy E. Grayson (https://sketchfab.com/JeremyGrayson)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/robotic-welding-arm-1d8abd370a674db0a4f9134e38ecfeef
title: Robotic Welding Arm
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()

  useFrame((state, delta) => {
    //group.current.rotation.y += 0.01
    //console.log(group.current.position.y)
  })

  const { nodes, materials } = useGLTF('/WeldingArm.gltf')
  return (
    <group
      //rotation={[-Math.PI / 2, 0, 0]}
      ref={group}
      {...props}
      dispose={null}
    >
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
      <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
    </group>
  )
}

useGLTF.preload('/WeldingArm.gltf')
