/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: jamesbwinfrey (https://sketchfab.com/jamesbwinfrey)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/robotic-arm-094bee030ef04f49bd5cc4f0500da259
title: Robotic Arm
*/

import React, { useRef, useState } from 'react'
import { MeshDistortMaterial, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const [spin, setSpin] = useState()

  useFrame(async (state, delta) => {
    if (spin) {
      group.current.rotation.y += 0.5
    }
  })

  const color = '#7733ff'
  const { nodes, materials } = useGLTF('/RoboticArmDuckish.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        // onClick={() => {
        //   props.onClick()
        //   setSpin(true)
        //   setTimeout(() => {
        //     setSpin(false)
        //   }, 400)
        // }}
        scale={0.03}
        position={[-60, -30, 40]}
        rotation={[Math.PI / 2, 1.57, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
        >
          {/* <meshLambertMaterial attach="material" color={color} /> */}
        </mesh>
        <mesh
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
        >
          {/* <meshLambertMaterial attach="material" color={color} /> */}
        </mesh>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={nodes.Object_4.material}
        >
          {/* <meshLambertMaterial attach="material" color={color} /> */}
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/RoboticArmDuckish.gltf')
