/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: PewPew (https://sketchfab.com/Pew.Pew)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hacker-laptop-803cf6b3a1ac4de9b3306e9c119516c3
title: Hacker Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Laptop.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[986.63, 1317.45, 59.35]}
          >
            <mesh
              geometry={nodes.Laptop_laptop_material_0.geometry}
              material={materials.laptop_material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Laptop.gltf')
