/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Cyberluna (https://sketchfab.com/anamariadiasandrade)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/graduation-86895e10baf54c46896823394766fb86
title: Graduation
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/graduation.gltf')
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group rotation={[-1.1, -0.1, 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 1.17, 0]}
            rotation={[0, Math.PI / 4, 0]}
            scale={[3.33, 1.24, 3.33]}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials['Material.001']}
            />
          </group>
          <group
            position={[-0.63, 0.86, -7.1]}
            rotation={[0, Math.PI / 4, Math.PI / 2]}
          >
            <mesh
              geometry={nodes.Object_6.geometry}
              material={nodes.Object_6.material}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials['Material.003']}
            />
          </group>
          <group position={[0, 3.64, 0]} scale={[5.97, 1, 0.48]}>
            <mesh
              geometry={nodes.Object_9.geometry}
              material={nodes.Object_9.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/graduation.gltf')
