/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Cyberluna (https://sketchfab.com/anamariadiasandrade)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/graduation-86895e10baf54c46896823394766fb86
title: Graduation
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { bool, any } from 'prop-types'
import { vel_scale, vel_scale_spin } from '../../utils/calculations'

Model.propTypes = {
  animate: bool,
  time: any,
}

export default function Model({ ...props }) {
  const group = useRef()
  const [spun, setSpun] = useState(false)
  let e_time
  const animation_time = 3000
  const ry = 0.01
  const vy = 0.01
  let rsy, vsy

  useFrame((state, delta) => {
    if (!props.animate) return

    if (!spun) {
      const t = 1000
      vsy = vel_scale_spin(Date.now() - props.time, 0, t, 0, 3.1415)
      group.current.rotation.y += 0.2 * vsy
      setSpun(Date.now() - props.time >= t ? true : false)
      return
    }

    e_time = (Date.now() - props.time) % animation_time
    vsy = vel_scale(e_time, 0, animation_time, 0, 2 * 3.1415)
    rsy = vel_scale(e_time, 0, 3000, 0, 2 * 3.1415)
    group.current.position.y += vy * vsy
    group.current.rotation.y += ry * rsy
  })

  const { nodes, materials } = useGLTF('/graduation.gltf')
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group rotation={[-1.1, -0.1, 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 1.17, 0]}
            rotation={[0, Math.PI / 4, 0]}
            scale={[3.33, 1.24, 3.33]}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials['Material.001']}
            />
          </group>
          <group
            position={[-0.63, 0.86, -7.1]}
            rotation={[0, Math.PI / 4, Math.PI / 2]}
          >
            <mesh
              geometry={nodes.Object_6.geometry}
              material={nodes.Object_6.material}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials['Material.003']}
            />
          </group>
          <group position={[0, 3.64, 0]} scale={[5.97, 1, 0.48]}>
            <mesh
              geometry={nodes.Object_9.geometry}
              material={nodes.Object_9.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/graduation.gltf')
