/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jean Nshuti (https://sketchfab.com/2nchy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/glowing-headphones-47e722ba850c4831bf9b60e7e24dd461
title: Glowing Headphones
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { array, bool, number } from 'prop-types'
import { vel_scale } from '../../utils/calculations'

Model.propTypes = {
  animate: bool,
  time: number,
  scale: number,
  position: array,
  rotation: array,
}

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/GlowingHeadphones.gltf')
  let e_time
  const animation_time = 3000
  const ry = 0.01
  const vy = 0.01
  let rsy, vsy

  useFrame((state, delta) => {
    if (!props.animate) return

    e_time = (Date.now() - props.time) % animation_time
    vsy = vel_scale(e_time, 0, animation_time, 0, 2 * 3.1415)
    rsy = vel_scale(e_time, 0, 3000, 0, 2 * 3.1415)
    group.current.position.y += vy * vsy
    group.current.rotation.y += ry * rsy
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.mesh_0.geometry}
              material={materials['Material.001']}
            />
            <mesh
              geometry={nodes.mesh_1.geometry}
              material={materials['Material.002']}
            />
            <mesh
              geometry={nodes.mesh_2.geometry}
              material={materials['Material.003']}
            />
            <mesh
              geometry={nodes.mesh_3.geometry}
              material={materials['Material.004']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/GlowingHeadphones.gltf')
