/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jean Nshuti (https://sketchfab.com/2nchy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/glowing-headphones-47e722ba850c4831bf9b60e7e24dd461
title: Glowing Headphones
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { array, bool, number } from 'prop-types'

Model.propTypes = {
  animate: bool,
  time: number,
  scale: number,
  position: array,
  rotation: array,
}

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/GlowingHeadphones.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.mesh_0.geometry}
              material={materials['Material.001']}
            />
            <mesh
              geometry={nodes.mesh_1.geometry}
              material={materials['Material.002']}
            />
            <mesh
              geometry={nodes.mesh_2.geometry}
              material={materials['Material.003']}
            />
            <mesh
              geometry={nodes.mesh_3.geometry}
              material={materials['Material.004']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/GlowingHeadphones.gltf')
