/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OneSteven (https://sketchfab.com/Steven007)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/hp-probook-87ea3eff834a49b992591cd086d20310
title: HP ProBook
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { number } from 'prop-types'

Model.propTypes = {
  scale: number,
}

export default function Model({ ...props }) {
  const group = useRef()

  let vy = 0.001
  const absoluteLimit = 0.6

  useFrame((state, delta) => {
    group.current.rotation.y += vy
    if (
      group.current.rotation.y > absoluteLimit ||
      group.current.rotation.y < -absoluteLimit
    ) {
      vy *= -1
    }
  })

  const { nodes, materials, animations } = useGLTF('/hp.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={props.scale} rotation={[5.5, 0, 0]}>
        <group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              name="display"
              position={[-0.25, 6.13, -16.44]}
              rotation={[2.62, 0, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                geometry={nodes.display_alu_0.geometry}
                material={nodes.display_alu_0.material}
              />
              <mesh
                geometry={nodes.display_chr_0.geometry}
                material={materials.material_9}
              />
              <mesh
                geometry={nodes.display_plastic_0.geometry}
                material={nodes.display_plastic_0.material}
              />
              <mesh
                geometry={nodes.display_scr_0.geometry}
                material={materials.material_10}
              />
            </group>
            <group
              position={[1.8, 5.84, 0.19]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                geometry={nodes.body000_alu_0.geometry}
                material={nodes.body000_alu_0.material}
              />
              <mesh
                geometry={nodes.body000_fgp_0.geometry}
                material={materials.material_1}
              />
              <mesh
                geometry={nodes.body000_rubba_0.geometry}
                material={materials.rubba}
              />
              <mesh
                geometry={nodes.body000_plastic_0.geometry}
                material={nodes.body000_plastic_0.material}
              />
              <mesh
                geometry={nodes.body000_miscblack_0.geometry}
                material={materials.miscblack}
              />
              <mesh
                geometry={nodes.body000_emit_0.geometry}
                material={materials.emit}
              />
              <mesh
                geometry={nodes.body000_red_0.geometry}
                material={materials.material_6}
              />
              <mesh
                geometry={nodes.body000_key_0.geometry}
                material={materials.material_7}
              />
              <mesh
                geometry={nodes.body000_label_0.geometry}
                material={materials.label}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hp.gltf')
