/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Rafa Andrade (https://sketchfab.com/rafa_andrade)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rocket-36ac04d6203545b1baf56c4cbf89349b
title: Rocket
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()

  const [reverse, setReverse] = useState()

  let ry = 0.005
  let vy = 0.005
  const limit = 2
  const buffer = 0.2

  useFrame((state, delta) => {
    if (!props.move) return

    group.current.rotation.y += ry
    group.current.position.y += vy * (reverse ? -1 : 1)
    //console.log(group.current.position.y)
    //console.log(reverse)

    setReverse(
      group.current.position.y > limit || group.current.position.y < -limit
        ? true
        : false
    )

    if (
      group.current.position.y > limit - buffer ||
      group.current.position.y < -limit + buffer
    ) {
      vy = 0.0025
    } else {
      vy = 0.005
    }
  })

  const { nodes, materials } = useGLTF('/rocket.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.blinn1SG} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.blinn5SG} />
        <mesh geometry={nodes.mesh_4.geometry} material={materials.phong1SG} />
        <mesh geometry={nodes.mesh_5.geometry} material={materials.phong2SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/rocket.gltf')
