/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Izzy (https://sketchfab.com/RigiT)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylized-treasure-map-cec61143abbc46bc99201b591942688b
title: Stylized Treasure Map
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/map.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={props.scale} rotation={[9, 10, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 226.19, 0]}
            rotation={[-1.97, -0.5, -0.72]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Treasure_Map_Treasure_Map_0.geometry}
              material={materials.Treasure_Map}
            />
          </group>
          <group
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[20189.41, 20189.41, 20189.41]}
          >
            {/* <mesh
              geometry={nodes.Plane_Background_0.geometry}
              material={materials.Background}
            /> */}
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/map.gltf')
