/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: kakaeka (https://sketchfab.com/kakaeka)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/arduino-uno-775a2bf901a74fd190f175f5f0dcf2d0
title: Arduino Uno
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  let vy = 0.1

  useFrame((state, delta) => {
    group.current.rotation.y += vy
  })
  const { nodes, materials } = useGLTF('/ArduinoUno.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.54, 0.14, 0]} scale={0}>
            <group
              position={[1099.07, -404.52, 265.29]}
              scale={[215.2, 179.53, 193.11]}
            >
              <mesh
                geometry={nodes.node_id375_Material_218_0.geometry}
                material={materials.Material_218}
              />
            </group>
            <group
              position={[1498.35, 256.85, 257.86]}
              scale={[388.99, 42.74, 194.49]}
            >
              <mesh
                geometry={nodes.node_id364_Material_222_0.geometry}
                material={materials.Material_222}
              />
            </group>
            <group position={[0.12, -106.06, 0]}>
              <group
                position={[1294.33, -285.42, 238.14]}
                scale={[101.86, 101.81, 17.44]}
              >
                <mesh
                  geometry={nodes.node_id345_Material_230_0.geometry}
                  material={materials.Material_230}
                />
              </group>
              <group
                position={[1255.71, -285.45, 847.44]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
              >
                <group
                  position={[329.73, -579.81, 799.56]}
                  rotation={[Math.PI, 0.55, -Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_234_0.geometry}
                    material={materials.Material_234}
                  />
                </group>
                <group
                  position={[-190.82, -961.53, 293.19]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <group
                    position={[-35.41, 471.78, 310.82]}
                    rotation={[-Math.PI / 2, -0.3, -Math.PI]}
                  >
                    <group
                      rotation={[-Math.PI / 2, 0, 2.85]}
                      scale={[1160.08, 822.75, 580.04]}
                    >
                      <mesh
                        geometry={nodes.node_id293_Material_258_0.geometry}
                        material={materials.Material_258}
                      />
                    </group>
                  </group>
                  <group
                    position={[-490.4, 610.78, 371.87]}
                    rotation={[-Math.PI / 2, -0.3, -Math.PI]}
                  >
                    <group
                      rotation={[Math.PI, 0.29, -Math.PI]}
                      scale={[254.53, 183.69, 207.85]}
                    >
                      <mesh
                        geometry={nodes.node_id294_Material_260_0.geometry}
                        material={materials.Material_260}
                      />
                    </group>
                  </group>
                </group>
                <group
                  position={[-190.82, -961.53, 293.19]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <group
                    position={[383.2, 786.61, 283.74]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={[0.32, 0.32, 0.32]}
                  >
                    <group
                      position={[845.24, 294.94, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id170_Material_53_0.geometry}
                        material={materials.Material_53}
                      />
                    </group>
                    <group
                      position={[747.41, 297.87, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id170_Material_55_0.geometry}
                        material={materials.Material_55}
                      />
                    </group>
                    <group
                      position={[942.99, 292.04, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id170_Material_57_0.geometry}
                        material={materials.Material_57}
                      />
                    </group>
                    <group
                      position={[745.47, 387.87, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id170_Material_59_0.geometry}
                        material={materials.Material_59}
                      />
                    </group>
                    <group
                      position={[843.3, 384.94, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id170_Material_61_0.geometry}
                        material={materials.Material_61}
                      />
                    </group>
                    <group
                      position={[941.05, 382.03, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id170_Material_63_0.geometry}
                        material={materials.Material_63}
                      />
                    </group>
                  </group>
                  <group
                    position={[-513.49, 655.97, 283.74]}
                    scale={[0.32, 0.32, 0.32]}
                  >
                    <group
                      position={[845.24, 294.94, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id184_Material_65_0.geometry}
                        material={materials.Material_65}
                      />
                    </group>
                    <group
                      position={[843.3, 384.94, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id184_Material_67_0.geometry}
                        material={materials.Material_67}
                      />
                    </group>
                    <group
                      position={[747.41, 297.87, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id184_Material_69_0.geometry}
                        material={materials.Material_69}
                      />
                    </group>
                    <group
                      position={[745.47, 387.87, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id184_Material_71_0.geometry}
                        material={materials.Material_71}
                      />
                    </group>
                    <group
                      position={[942.99, 292.04, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id184_Material_73_0.geometry}
                        material={materials.Material_73}
                      />
                    </group>
                    <group
                      position={[941.05, 382.03, 200.01]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 0.17, 1]}
                    >
                      <mesh
                        geometry={nodes.node_id184_Material_75_0.geometry}
                        material={materials.Material_75}
                      />
                    </group>
                  </group>
                </group>
                <group
                  position={[361.04, -579.81, 800.64]}
                  rotation={[Math.PI, 0.55, -Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_236_0.geometry}
                    material={materials.Material_236}
                  />
                </group>
                <group
                  position={[292.43, -579.81, 800.16]}
                  rotation={[Math.PI, 0.55, -Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_238_0.geometry}
                    material={materials.Material_238}
                  />
                </group>
                <group
                  position={[294.93, -579.81, 769.53]}
                  rotation={[Math.PI, 0.55, -Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_240_0.geometry}
                    material={materials.Material_240}
                  />
                </group>
                <group
                  position={[332.23, -579.81, 768.93]}
                  rotation={[Math.PI, 0.55, -Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_242_0.geometry}
                    material={materials.Material_242}
                  />
                </group>
                <group
                  position={[360.29, -579.81, 770.76]}
                  rotation={[Math.PI, 0.55, -Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_244_0.geometry}
                    material={materials.Material_244}
                  />
                </group>
                <group
                  position={[556.46, -579.81, 14.3]}
                  rotation={[-Math.PI, 0.55, Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_246_0.geometry}
                    material={materials.Material_246}
                  />
                </group>
                <group
                  position={[588.37, -579.81, 14.71]}
                  rotation={[Math.PI, 0.55, -Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_248_0.geometry}
                    material={materials.Material_248}
                  />
                </group>
                <group
                  position={[588.32, -579.81, 45.33]}
                  rotation={[Math.PI, 0.55, -Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_250_0.geometry}
                    material={materials.Material_250}
                  />
                </group>
                <group
                  position={[557.89, -579.81, 46.93]}
                  rotation={[-Math.PI, 0.55, Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_252_0.geometry}
                    material={materials.Material_252}
                  />
                </group>
                <group
                  position={[557.38, -579.81, 77.73]}
                  rotation={[-Math.PI, 0.55, Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_254_0.geometry}
                    material={materials.Material_254}
                  />
                </group>
                <group
                  position={[587.95, -579.81, 75.42]}
                  rotation={[Math.PI, 0.55, -Math.PI]}
                  scale={[0.11, 0.4, 0.15]}
                >
                  <mesh
                    geometry={nodes.node_id304_Material_256_0.geometry}
                    material={materials.Material_256}
                  />
                </group>
              </group>
              <group
                position={[1406.61, -281.38, 227.39]}
                scale={[100.32, 98.9, 37]}
              >
                <mesh
                  geometry={nodes.node_id345_Material_232_0.geometry}
                  material={materials.Material_232}
                />
              </group>
            </group>
            <group
              position={[1873.73, 261.88, 258.63]}
              scale={[317.21, 42.42, 161.39]}
            >
              <mesh
                geometry={nodes.node_id364_Material_224_0.geometry}
                material={materials.Material_224}
              />
            </group>
            <group
              position={[1911.1, -476.15, 256.21]}
              scale={[244.84, 42.52, 113.51]}
            >
              <mesh
                geometry={nodes.node_id364_Material_226_0.geometry}
                material={materials.Material_226}
              />
            </group>
            <group
              position={[1601.09, -475.27, 258.05]}
              scale={[319.46, 43.44, 158.38]}
            >
              <mesh
                geometry={nodes.node_id364_Material_228_0.geometry}
                material={materials.Material_228}
              />
            </group>
            <group
              position={[1750.57, -271.02, 229.3]}
              scale={[567.28, 137.73, 263.34]}
            >
              <mesh
                geometry={nodes.node_id375_Material_220_0.geometry}
                material={materials.Material_220}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ArduinoUno.gltf')
