/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ioannapnl (https://sketchfab.com/ioannapnl)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/laptop-9b45e7a38db844bd939dbc0d5ea19737
title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/WhiteLaptop.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.material} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.Mat_1} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.Mat_2} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.Mat_3} />
      </group>
    </group>
  )
}

useGLTF.preload('/WhiteLaptop.gltf')
