/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ioannapnl (https://sketchfab.com/ioannapnl)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/laptop-9b45e7a38db844bd939dbc0d5ea19737
title: Laptop
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { array, bool, number } from 'prop-types'
import { useFrame } from '@react-three/fiber'
import { vel_scale } from '../../utils/calculations'

Model.propTypes = {
  move: bool,
  rotation: array,
  position: array,
  scale: number,
  time: number,
}

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/WhiteLaptop.gltf')

  let ry = 0.005
  let vy = 0.005
  const anim_time = {
    x: 1000,
    y: 3000,
    z: 1000,
  }
  let vsy, rsy
  let e_time

  useFrame((state, delta) => {
    if (!props.move) return

    e_time = (Date.now() - props.time) % anim_time.y
    vsy = vel_scale(e_time, 0, anim_time.y, 0, 2 * 3.1415)
    group.current.position.y += vy * vsy
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.material} />
        {/* <meshLambertMaterial attach="material" color={color} /> */}
        <mesh geometry={nodes.mesh_0.geometry} material={materials.material} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.Mat_1} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.Mat_2} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.Mat_3} />
      </group>
    </group>
  )
}

useGLTF.preload('/WhiteLaptop.gltf')
